import React from 'react';

// Pre-computed codepoint → CDN URL map for all tunaOS project emojis.
// Generated by scripts/emoji-url.mjs. Add new entries as needed.
const CDN_BASE = 'https://fonts.gstatic.com/s/e/notoemoji/latest';

const EMOJI_MAP: Record<string, string> = {
  '🐟': `${CDN_BASE}/1f41f/512.gif`,
  '🐠': `${CDN_BASE}/1f420/512.gif`,
  '🍣': `${CDN_BASE}/1f363/512.gif`,
  '🎣': `${CDN_BASE}/1f3a3/512.gif`,
  '🧰': `${CDN_BASE}/1f9f0/512.gif`,
  '📦': `${CDN_BASE}/1f4e6/512.gif`,
  '💻': `${CDN_BASE}/1f4bb/512.gif`,
  '🟠': `${CDN_BASE}/1f7e0/512.gif`,
  '🏔️': `${CDN_BASE}/1f3d4/512.gif`,
  '💪': `${CDN_BASE}/1f4aa/512.gif`,
  '🔧': `${CDN_BASE}/1f527/512.gif`,
  '🍺': `${CDN_BASE}/1f37a/512.gif`,
  '⌨️': `${CDN_BASE}/2328/512.gif`,
  '🖥️': `${CDN_BASE}/1f5a5/512.gif`,
  '📖': `${CDN_BASE}/1f4d6/512.gif`,
  '🚀': `${CDN_BASE}/1f680/512.gif`,
  '📋': `${CDN_BASE}/1f4cb/512.gif`,
  '✨': `${CDN_BASE}/2728/512.gif`,
  '🛡️': `${CDN_BASE}/1f6e1/512.gif`,
  '⚡': `${CDN_BASE}/26a1/512.gif`,
};

type Props = {
  emoji: string;
  size?: number;
  className?: string;
  alt?: string;
};

export default function AnimatedEmoji({emoji, size = 32, className, alt}: Props) {
  const src = EMOJI_MAP[emoji];
  if (!src) {
    // Fallback: render the static emoji character
    return <span className={className} style={{fontSize: size}} role="img" aria-label={alt || emoji}>{emoji}</span>;
  }
  return (
    <img
      src={src}
      alt={alt || emoji}
      width={size}
      height={size}
      className={className}
      style={{display: 'inline-block', imageRendering: 'auto'}}
      loading="lazy"
    />
  );
}
