#!/usr/bin/env node

// ASD-STE100 Simplified Technical English linter for this site's prose.
//
// Reads Markdown, throws away everything that is not prose — front matter,
// code fences, tables, HTML/JSX blocks, link targets — and applies the rules
// in ste-rules.mjs to what is left. Checking a code block against a controlled
// natural language would report nothing useful and hide the findings that
// matter.
//
// Usage:
//   node scripts/ste-lint.mjs                 # every tracked doc and blog post
//   node scripts/ste-lint.mjs docs/intro.md   # named files
//   node scripts/ste-lint.mjs --summary       # counts per file, no detail
//   node scripts/ste-lint.mjs --max 0         # fail if any finding remains
//
// Exit code is 1 when the finding count is above --max, so CI can hold a
// budget and ratchet it down rather than demanding perfection on day one.

import {readFileSync, readdirSync, statSync} from 'node:fs';
import {join, relative} from 'node:path';
import {checkSentence, checkParagraphLength, splitSentences} from './ste-rules.mjs';
import {isSyncedIndex, HAND_AUTHORED} from './sync-org-docs.mjs';

const ROOT = process.cwd();

// ── which prose does this repo answer for ─────────────────────────────────────
//
// Markdown under docs/<slug>/ is generated by sync-org-docs.mjs. Its prose is
// authored in another repository and is overwritten here on every sync, so
// findings against it are noise: the fix belongs upstream, and an edit made here
// disappears at the next sync. Everything else is this repo's to answer for, so
// getting the line in the right place matters in both directions.

// GENERATED_MARKER is the absolute-GitHub-link shape sync-org-docs.mjs leaves
// behind when it rewrites a repo-relative link.
//
// It is a weak signal in both directions and is no longer what decides whether
// a tree is generated (see generatedDirs below):
//
//   * it is not necessary — a synced file that contained no relative link never
//     gets the mark, which is how seven synced files stayed in the budget (#102)
//   * it is not sufficient — a hand-written page that links to a file on GitHub
//     carries the identical shape. docs/faq.md and docs/community.md link to
//     tunaOS/blob/main/CONTRIBUTING.md by hand and are marked generated today.
//
// It survives only as the per-file fallback in main(). Removing it there is a
// separate change with a much larger budget consequence, filed separately.
const GENERATED_MARKER = /github\.com\/tuna-os\/[a-zA-Z0-9._-]+\/blob\/main/;

// isGenerated reports whether a file carries the rewritten-link mark. Prefer
// generatedDirs: this answers "does the file link to GitHub", not "was the file
// written by the sync".
export function isGenerated(content) {
  return GENERATED_MARKER.test(content);
}

// generatedDirs finds the docs/<slug>/ trees that sync-org-docs.mjs owns.
//
// The question is who wrote the tree, so the answer comes from the writer. Every
// tree the sync creates gets an index page whose front matter the sync composed
// itself — isSyncedIndex, exported from sync-org-docs.mjs, matches exactly that
// template and nothing else. One such file means the directory came from another
// repository, and none of it should be rewritten here: the next sync reverts it.
//
// HAND_AUTHORED, also from sync-org-docs.mjs, is the same list the sync consults
// before it refuses to overwrite a tree. Reusing it means a page the sync will
// not touch is a page the checker does hold to the style rules, and one edit
// keeps both true.
//
// What this deliberately does not do is ask GitHub which repos exist. The org
// listing is not available to a lint job — no gh, no token, no network — and it
// is also the wrong question: docs/dakota-iso/ was written by a sync of a repo
// that is no longer in the tuna-os listing at all, so a listing-derived rule
// would put its nine findings back into the budget as prose to fix by hand.
//
// Known limit: the index page exists only when the source repo has a README. A
// repo with docs/ and no README would produce a tree of subpages alone, and
// subFrontmatter is sidebar_position plus a quoted title — the shape a person
// writing a page by hand uses as well, so matching on it would take pages this
// repo owns out of the checker. Every synced tree today has an index page. The
// failure if one does not is the loud one: its findings enter the budget and
// the next PR sees them, rather than prose quietly going unchecked.
export function generatedDirs(root = ROOT) {
  const dirs = new Set();
  let entries = [];
  try {
    entries = readdirSync(join(root, 'docs'));
  } catch {
    return dirs;
  }
  for (const entry of entries) {
    if (HAND_AUTHORED.has(entry)) continue;
    const dir = join(root, 'docs', entry);
    let stat;
    try {
      stat = statSync(dir);
    } catch {
      continue;
    }
    if (!stat.isDirectory()) continue;
    for (const file of walk(dir)) {
      if (isSyncedIndex(readFileSync(file, 'utf8'))) {
        dirs.add(dir);
        break;
      }
    }
  }
  return dirs;
}

// A file may opt out with a reason, on its first line:
//   <!-- ste-disable-file: this page is a list of external titles -->
// and a region may opt out between markers:
//   <!-- ste-disable: quoted release notes -->  ...  <!-- ste-enable -->
//
// The reason is required. An escape hatch with no explanation becomes the
// default, and then the checker measures nothing.
const DISABLE_FILE = /<!--\s*ste-disable-file:\s*(.+?)\s*-->/;
const DISABLE_BLOCK = /<!--\s*ste-disable:\s*.+?\s*-->[\s\S]*?<!--\s*ste-enable\s*-->/g;

// disabledReason returns why a file opted out, or null.
export function disabledReason(content) {
  const match = content.match(DISABLE_FILE);
  return match ? match[1] : null;
}

// stripNonProse removes everything the rules must not see. Order matters:
// fenced code first, or a fence containing a heading confuses the rest.
export function stripNonProse(markdown) {
  let text = markdown;

  // Regions the author opted out of, with a reason.
  text = text.replace(DISABLE_BLOCK, '');

  // Front matter.
  text = text.replace(/^---\n[\s\S]*?\n---\n/, '');
  // Fenced code, including ```mdx-code-block and ~~~ fences.
  text = text.replace(/^```[\s\S]*?^```$/gm, '');
  text = text.replace(/^~~~[\s\S]*?^~~~$/gm, '');
  // Indented code blocks.
  text = text.replace(/^(?: {4}|\t).*$/gm, '');
  // JSX / HTML blocks and inline tags — Docusaurus pages are full of them.
  text = text.replace(/^<[A-Za-z][\s\S]*?^\/?>$/gm, '');
  text = text.replace(/<[^>]+>/g, ' ');
  // Import/export lines in .mdx.
  text = text.replace(/^(?:import|export)\s.*$/gm, '');
  // Tables: cell text is fragmentary and has no sentence structure.
  text = text.replace(/^\|.*\|$/gm, '');
  // Headings are labels, not sentences.
  text = text.replace(/^#{1,6}\s.*$/gm, '');
  // Images and link targets — keep the link text, drop the URL.
  text = text.replace(/!\[[^\]]*\]\([^)]*\)/g, ' ');
  text = text.replace(/\[([^\]]*)\]\([^)]*\)/g, '$1');
  // Reference definitions and bare URLs.
  text = text.replace(/^\[[^\]]+\]:\s*\S+.*$/gm, '');
  text = text.replace(/https?:\/\/\S+/g, ' ');
  // Inline code: a symbol is not a word STE has an opinion about.
  text = text.replace(/`[^`]*`/g, ' ');
  // Badges/admonition markers.
  text = text.replace(/^:::.*$/gm, '');

  return text;
}

// blocks splits prose into paragraphs and list items, tagging list items and
// numbered steps as procedural — STE holds instructions to a shorter limit
// than description, and that is where the difference lives in a docs site.
export function blocks(prose) {
  const out = [];
  for (const chunk of prose.split(/\n{2,}/)) {
    const trimmed = chunk.trim();
    if (!trimmed) continue;

    const lines = trimmed.split('\n');
    const listItem = /^\s*(?:[-*+]|\d+[.)])\s+/;

    // A chunk can be a paragraph, a list, or a paragraph with a list stuck to
    // it — Markdown does not need a blank line between them. Joining those
    // into one "sentence" produced findings like a seven-word noun cluster
    // made of three separate bullets, so the lead-in and the items are
    // separated here.
    const lead = [];
    let seenItem = false;
    for (const line of lines) {
      if (listItem.test(line)) {
        seenItem = true;
        const text = line.replace(listItem, '').trim();
        if (text) out.push({text, procedural: true});
        continue;
      }
      if (seenItem) {
        // A continuation line of the previous item.
        const previous = out[out.length - 1];
        if (previous) previous.text += ' ' + line.trim();
        continue;
      }
      lead.push(line.trim());
    }
    if (lead.length) {
      out.push({text: lead.join(' '), procedural: false});
    }
  }
  return out;
}

// lintText returns every finding in one document's prose.
export function lintText(markdown) {
  const prose = stripNonProse(markdown);
  const findings = [];

  for (const block of blocks(prose)) {
    const sentences = splitSentences(block.text);
    if (!block.procedural) {
      const long = checkParagraphLength(sentences);
      if (long) findings.push({...long, sentence: block.text.slice(0, 60) + '…'});
    }
    for (const sentence of sentences) {
      for (const finding of checkSentence(sentence, {procedural: block.procedural})) {
        findings.push({...finding, sentence});
      }
    }
  }
  return findings;
}

// ── walking the repository ────────────────────────────────────────────────────

const SKIP_DIRS = new Set(['node_modules', '.git', 'build', '.docusaurus', 'static']);

function walk(dir, out = []) {
  for (const entry of readdirSync(dir)) {
    if (SKIP_DIRS.has(entry)) continue;
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) {
      walk(full, out);
    } else if (/\.mdx?$/.test(entry)) {
      out.push(full);
    }
  }
  return out;
}

function defaultTargets() {
  const targets = [];
  for (const dir of ['docs', 'blog']) {
    try {
      targets.push(...walk(join(ROOT, dir)));
    } catch {
      // The directory may not exist in a partial checkout.
    }
  }
  for (const file of ['README.md', 'CONTRIBUTING.md', 'SECURITY.md', 'CODE_OF_CONDUCT.md']) {
    try {
      statSync(join(ROOT, file));
      targets.push(join(ROOT, file));
    } catch {
      // Optional.
    }
  }
  return targets;
}

function main() {
  const args = process.argv.slice(2);
  const summary = args.includes('--summary');
  const includeGenerated = args.includes('--include-generated');
  const maxIndex = args.indexOf('--max');
  const max = maxIndex >= 0 ? Number(args[maxIndex + 1]) : Infinity;
  const files = args.filter((a) => !a.startsWith('--') && !/^\d+$/.test(a));
  const targets = files.length ? files.map((f) => join(ROOT, f)) : defaultTargets();

  let total = 0;
  let skipped = 0;
  const perFile = [];
  const optedOut = [];
  const generated = includeGenerated ? new Set() : generatedDirs();

  for (const file of targets) {
    const content = readFileSync(file, 'utf8');
    const inGeneratedTree = [...generated].some((d) => file.startsWith(d + '/'));
    if (!includeGenerated && (inGeneratedTree || isGenerated(content))) {
      skipped++;
      continue;
    }
    const reason = disabledReason(content);
    if (reason) {
      optedOut.push({file: relative(ROOT, file), reason});
      continue;
    }
    const findings = lintText(content);
    if (!findings.length) continue;
    total += findings.length;
    perFile.push({file: relative(ROOT, file), findings});
  }

  perFile.sort((a, b) => b.findings.length - a.findings.length);

  for (const {file, findings} of perFile) {
    if (summary) {
      console.log(`${String(findings.length).padStart(5)}  ${file}`);
      continue;
    }
    console.log(`\n${file}  (${findings.length})`);
    for (const f of findings) {
      console.log(`  ${f.rule}  ${f.message}`);
      if (f.sentence) console.log(`         ${f.sentence.slice(0, 100)}`);
    }
  }

  console.log(`\n${total} finding(s) across ${perFile.length} file(s)`);
  for (const {file, reason} of optedOut) {
    console.log(`opted out: ${file} — ${reason}`);
  }
  if (skipped) {
    console.log(`${skipped} generated file(s) skipped — their prose is authored upstream ` +
      `(pass --include-generated to check them anyway)`);
    // Name the trees. A tree that drops out of this list is prose the checker
    // has started to hold this repo responsible for, and a tree that appears in
    // it wrongly is prose nobody is checking — both are worth seeing in the log
    // rather than inferring from a total that moved.
    const trees = [...generated].map((d) => relative(ROOT, d)).sort();
    if (trees.length) console.log(`generated trees: ${trees.join(' ')}`);
  }
  if (total > max) {
    console.error(`\nSTE budget exceeded: ${total} > ${max}`);
    process.exit(1);
  }
}

// Only run when invoked directly, so the tests can import the helpers.
if (process.argv[1] && process.argv[1].endsWith('ste-lint.mjs')) {
  main();
}
